steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE}'
      - '.'
images:
  - '${_IMAGE}'
substitutions:
  _IMAGE: 'gcr.io/${PROJECT_ID}/shrine-stair-trainer'
options:
  logging: CLOUD_LOGGING_ONLY
